change in branch
bgardner-edu/HelloFromBradley pull request #1
Opened 2021-01-28 23:53 UTC by bgardner-edu

test

2021-01-28 23:54 UTC, DrParsley commented
Looks nice

2021-01-28 23:55 UTC, DrParsley commented on src/gardner/Main.java
> +	    System.out.println("Hello, my name is In a new Branch");
NICE!

2021-01-29 00:02 UTC, DrParsley approved these changes

2021-01-29 00:03 UTC, DrParsley commented
Looks okay I guess

2021-01-29 00:03 UTC, Bozo-Cake approved these changes

2021-01-29 00:04 UTC, Bozo-Cake requested changes
change name to Johnny number 5

2021-01-29 00:05 UTC, merged